### ISSUE TITLE
Integrity constraint violation: 1048 Column 'name' cannot be null

### ISSUE THREAD

**Issue by jringeisen** [lorisleiva/blog-google-calendar#1]
If the google event name ($googleEvent->summary) is empty it causes an exception and the sync fails. I added a turnery, maybe there is a better option, but this works for me.

SynchronizeGoogleEvents.php

`'name' => $googleEvent->summary ? $googleEvent->summary : 'Event',`

**Comment by lorisleiva** [comment]
Hi Jonathon 👋 

That's a good point. I'm going to go through the mapping process and provide default values to fallback to.

I'll let you know once that's done since I have to organise this repo a bit better first (like one branch per episode, etc.)

Thanks for your contribution.

**Comment by jringeisen** [comment]
@lorisleiva anytime, I love the way you set this up. I have users that sync their dashboard calendars to google so this course is perfect. I'm going to play around with it because there is some functionality that I need such as creating an event on their dashboard and syncing it to google, so instead of syncing their dashboard with their google account, syncing it both ways. I'm not sure if you plan to do this in one of the episodes.

**Comment by lorisleiva** [comment]
Yes at the moment I only have the next article on webhook synchronization planned but I can certainly do a few more to account for creating new Google resources directly from the application. I'll have to play with it a bit more first but it shouldn't be too difficult with our Google service wrapper 🙂

**Comment by lorisleiva** [comment]
I have fixed this issue on part 2 and cherry picked it for part 1. It should be all good now. Thanks again for reporting this.

**Comment by jringeisen** [comment]
@lorisleiva awesome, thanks! Are you planning to end this after part 3? Anyway, you can do a part on creating an event in Laravel and having it sync to google?

**Comment by lorisleiva** [comment]
Of course, I was planning to stop after the third part but nothing stops me from writing a few more after that 😉

**Comment by jringeisen** [comment]
@lorisleiva you're awesome, this is going to help me so much. Thank you!
