### ISSUE TITLE
Suggestion: Turn this into a package

### ISSUE THREAD

**Issue by flaviomsb** [lorisleiva/blog-google-calendar#3]
I think this project is very well made and I was going to use it in the current product I am working on but... I am strongly against cannibalizing people's code. 

I would like to suggest that you refactor this into a package so other people can extend it properly at same time that the credits for your work are preserved.

Thanks and congrats again on this tutorial.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thank you for your suggestion. I also think it's a good idea but at the moment I'm working on a new video course so I don't have time to release a new ambitious package.

That being said I have no problem whatsoever in letting you create such a package by reusing what you've learned in this tutorial. After all, that's the beauty of open-source. 🙂 

Let me know if you need some help down the road. I'll leave this issue open until you have something you can share here.

Thanks again for open this issue. 👍
